### ISSUE TITLE
Shop.py hasn't been created for the shop in Koha

### ISSUE THREAD

**Issue by Animetality** [Nakukai/Koha#8]
**Koha's shop hasn't been implemented and the rough sketch hasn't even been stated. I'll add a pull request so you see if it should be added. I'll take care of everything in relation to the shop. All I would need is the items you want me to use and that should be it.**

**Comment by Katsuniya** [comment]
Alright. Just give me an alert when you're done and I'll review the pull request.

**Comment by Katsuniya** [comment]
Okay I just completed that. It's up to you to commit all the extra stuff when a new item is suppose to be available. No data about users should be included in this repo as usual.
